---
title: "EAMPD_analyse"
author: "Aurane Vernière"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE)
```

```{r}
library("readxl") 
library("here") 
install.packages(c("FactoMineR","factoextra")) 
library("FactoMineR") 
library("factoextra")
library("lubridate") 
library("dplyr") 
library("tidyverse")
library("ggplot2") 
#install.packages("nloptr")
#library("nloptr")
library("MASS")
install.packages("NlcOptim")
library("NlcOptim")
```

```{r}
# Chargement des bases de données
press_release<- read_excel(here("Dataset_EA-MPD.xlsx"), sheet = "Press Release Window") 
press_conference<-read_excel(here("Dataset_EA-MPD.xlsx"), sheet = "Press Conference Window") 
monetary_event<- read_excel(here("Dataset_EA-MPD.xlsx"), sheet = "Monetary Event Window")

```

```{r}
# Création de variables de dates utilisables 
monetary_event["date"]<-ymd(monetary_event$date) 
monetary_event["year"] <- year(monetary_event$date)
monetary_event["month"] <-month(monetary_event$date) 
monetary_event["day"] <- day(monetary_event$date)

press_release["date"]<-ymd(press_release$date) 
press_release["year"] <- year(press_release$date)
press_release["month"] <-month(press_release$date) 
press_release["day"] <- day(press_release$date)

press_conference["date"]<-ymd(press_conference$date) 
press_conference["year"] <- year(press_conference$date)
press_conference["month"] <-month(press_conference$date) 
press_conference["day"] <- day(press_conference$date)
```

```{r}
# Bases de données 
monetary_event_2012=monetary_event %>% filter(year>= 2012)
monetary_event_2020=monetary_event%>%filter(year>=2020)
monetary_event_2016=monetary_event%>%filter(year>=2016)
date=monetary_event_2012$date
#monetary_event_2012$date=format(monetary_event_2012$date, "%Y-%m-%d")

press_release_2020=press_release%>%filter(year>=2020)
press_release_2012=press_release%>%filter(year>=2012)
#press_release_2012$date=format(press_release_2012$date, "%Y-%m-%d")

press_conference_2020=press_conference%>%filter(year>=2020)
press_conference_2012=press_conference%>%filter(year>=2012)
#press_conference_2012$date=format(press_conference_2012$date, "%Y-%m-%d")
```

```{r}
# Création d'un vecteur avec toutes les dates
#date=monetary_event_2012$date 

# Création de la base de travail
monetary_event_work= monetary_event_2012[2:15]
#monetary_event_work=t(monetary_event_work)
#colnames(monetary_event_work)=date
```

```{r}
# Réalisation de l'ACP
PC.pca=prcomp(monetary_event_work, scale=TRUE)
fviz_eig(PC.pca, addlabels=TRUE, hjust = -0.3)+ylim(0,75)
```

```{r}
loadings_matrix=-1*PC.pca$rotation
x=-1*PC.pca$x
```

```{r}
fviz_pca_var(PC.pca, col.var = "steelblue")
```

```{r}
# Eigenvalues
eig.val <- get_eigenvalue(PC.pca)
  
# Results for Variables
res.var <- get_pca_var(PC.pca)
coord=res.var$coord          # Coordinates
contrib=res.var$contrib        # Contributions to the PCs
cos=res.var$cos2           # Quality of representation 

# Results for individuals
res.ind <- get_pca_ind(PC.pca)
coord_ind=res.ind$coord          # Coordinates
contrib_ind=res.ind$contrib        # Contributions to the PCs
cos_ind=res.ind$cos2           # Quality of representation 
```

```{r}
# Contributions des OIS à chacune des composantes de l'ACP
ind=get_pca_ind(PC.pca) 
fviz_pca_ind(PC.pca, repel=TRUE)
fviz_contrib(PC.pca, choice = "var", axes = 1)
fviz_contrib(PC.pca, choice = "var", axes = 2)
```

```{r}
# Evolution temporelle des annonces de taux 1 : variations totales des taux pour différents instruments 

ggplot(monetary_event_2020, aes(x=date))+ 
geom_line(aes(y = OIS_1M,color = "OIS_1M"))+ geom_line(aes(y = OIS_1Y, color = "OIS_1Y"))+
geom_line(aes(y = OIS_10Y, color = "OIS_10Y"))+ 
labs(x = "Date des annonces monétaires", y = "Variation du taux des instruments")+
scale_color_manual(values = c(OIS_1M = "coral4", OIS_1Y = "dimgray", OIS_10Y = "greenyellow"), labels = c("OIS_SW", "OIS_1M", "OIS_1Y"), name= "Instrument") + 
theme_bw()+ 
ggtitle("Evolution temporelle des variations surprise des taux")
```

```{r}
# Evolution temporelle des annonces de taux 2 :on trace les surprises pour OIS_1M
graph_data=data.frame(press_release_2020$date,
                    press_release_2020$OIS_1M,
                    press_conference_2020$OIS_1M,
                    monetary_event_2020$OIS_1M)

colnames(graph_data)=c("date","press_release","press_conference","monetary_event")

ggplot(graph_data, aes(x=date))+
  geom_line(aes(y = press_release,color = "press_release"))+ 
  geom_line(aes(y = press_conference, color = "press_conference"))+
  geom_line(aes(y = monetary_event, color = "monetary_event"))+
  scale_color_manual(values = c(press_release = "blue3", press_conference = "red", monetary_event= "chartreuse3"), labels = c("monetary event", "press conference", "press release"), name= "Window")+
  labs(x = "Date des annonces monétaires", y = "Variation du taux des OIS 1M")+
  theme_bw()+
  ggtitle("Evolution temporelle des variations surprise des taux \ndans chaque fenêtre")
```

```{r}
F1=x[,1]
F2=x[,2]
F=data.frame(date,F1,F2)
```

```{r}
F_2020=F%>%mutate(year=year(F$date), 
                  OIS_SW=monetary_event_2012$OIS_SW,
                  OIS_1M=monetary_event_2012$OIS_1M,
                  OIS_1Y=monetary_event_2012$OIS_1Y,
                  OIS_5Y=monetary_event_2012$OIS_5Y)%>%filter(year>=2020)

ggplot(F_2020,aes(x=date))+
  geom_line(aes(y=F1, color="First_Dimension"))+
  geom_line(aes(y=F2, color="Second_Dimension"))+
  scale_color_manual(values=c(First_Dimension="cadetblue4", Second_Dimension="brown4"), labels=c("Dimension 1","Dimension 2"), name="Légende")+
  labs(x="Dates des annonces monétaires", y="Componsantes de l'annonce")+
  theme_bw()+
  ggtitle("Evolution temporelle des deux composantes de l'annonce \nmonétaire trouvées via l'ACP")
```

```{r}
monetary_event_SR=merge(monetary_event_2012, F, by="date")
press_conference_SR=merge(press_conference_2012, F, by="date")
press_release_SR=merge(press_release_2012, F, by="date")

vars_PR=colnames(press_release_SR[2:15])
vars_PC=colnames(press_conference_SR[2:15])
```

```{r}
# Vérification des corrélations : Press_release

model_PR1_SR=lm(as.formula(paste("F1 ~", paste(vars_PR, collapse = "+"))), data=press_release_SR)
summary(model_PR1_SR)
model_PR2_SR=lm(as.formula(paste("F2 ~", paste(vars_PR, collapse = "+"))), data=press_release_SR)
summary(model_PR2_SR)
```

```{r}
# Vérification des corrélations : Press_conference

model_PC1_SR=lm(as.formula(paste("F1 ~", paste(vars_PR, collapse = "+"))), data=press_conference_SR)
summary(model_PC1_SR)
model_PC2_SR=lm(as.formula(paste("F2 ~", paste(vars_PR, collapse = "+"))), data=press_conference_SR)
summary(model_PC2_SR)
```

```{r}
# Fonction permettant la régression de chaque OIS d'une fenêtre sur les facteurs censés être Target et FG

get_regression_results <- function(df, dependent_var, independent_var) {
  model=lm(formula(paste(dependent_var, "~", independent_var)), data = df)
  coef <- round(coef(model)[2],3)
  p_value <- round(summary(model)$coefficients[2, 4],3)
  r_squared <- round(summary(model)$r.squared, 3)
  if (p_value <= 0.01) {
    significance <- "***"
  } else if (p_value <= 0.05) {
    significance <- "**"
  } else if (p_value <= 0.10) {
    significance <- "*"
  } else {
    significance <- ""
  }
  return(c(Coefficient = coef, `P-value` = p_value, `R-squared` = r_squared, Significance = significance))
}
```

```{r}
results_F1_PR <- sapply(vars_PR, function(var) get_regression_results(press_release_SR, var, "F1"))
results_F2_PR <- sapply(vars_PR, function(var) get_regression_results(press_release_SR, var, "F2"))
results_table_F1_PR <- t(as.data.frame(results_F1_PR))
results_table_F2_PR <- t(as.data.frame(results_F2_PR))

print(results_table_F1_PR)
print(results_table_F2_PR)
```

```{r}
results_F1_PC <- sapply(vars_PR, function(var) get_regression_results(press_conference_SR, var, "F1"))
results_F2_PC <- sapply(vars_PR, function(var) get_regression_results(press_conference_SR, var, "F2"))
results_table_F1_PC <- t(as.data.frame(results_F1_PC))
results_table_F2_PC <- t(as.data.frame(results_F2_PC))

print(results_table_F1_PC)
print(results_table_F2_PC)
```

```{r}
ggplot(F_2020,aes(x=date))+
  geom_line(aes(y=OIS_SW, color="OIS_SW"))+
  geom_line(aes(y=OIS_1M, color="OIS_1M"))+
  geom_line(aes(y=F2, color="Second_Dimension"))+
  scale_color_manual(values=c(OIS_SW="cadetblue4", OIS_1M="brown4",Second_Dimension="goldenrod3"), labels=c("OIS SW","OIS 1M","Dimension 2"), name="Légende")+
  labs(x="Dates des annonces monétaires")+
  theme_bw()+
  ggtitle("Evolution temporelle de la deuxième composante de l'ACP et \ndes surprises des OIS SW et 1M")
```

```{r}
ggplot(F_2020,aes(x=date))+
  geom_line(aes(y=OIS_1Y, color="OIS_1Y"))+
  geom_line(aes(y=OIS_5Y, color="OIS_5Y"))+
  geom_line(aes(y=F2, color="Second_Dimension"))+
  scale_color_manual(values=c(OIS_1Y="cadetblue4", OIS_5Y="brown4",Second_Dimension="goldenrod3"), labels=c("OIS 1Y","OIS 5Y","Dimension 2"), name="Légende")+
  labs(x="Dates des annonces monétaires")+
  theme_bw()+
  ggtitle("Evolution temporelle de la deuxième composante de l'ACP et \ndes surprises des OIS 1Y et 5Y")
```

```{r}
ggplot(F_2020,aes(x=date))+
  geom_line(aes(y=OIS_1M, color="OIS_1M"))+
  geom_line(aes(y=OIS_1Y, color="OIS_1Y"))+
  geom_line(aes(y=OIS_5Y, color="OIS_5Y"))+
  geom_line(aes(y=F1, color="First_Dimension"))+
  scale_color_manual(values=c(OIS_1M="darkgoldenrod1", OIS_1Y="darkorange1", OIS_5Y="brown4",First_Dimension="cadetblue4"), labels=c("Dimension 1","OIS 1M","OIS 1Y", "OIS 5Y"), name="Légende")+
  labs(x="Dates des annonces monétaires")+
  theme_bw()+
  ggtitle("Evolution temporelle de la première composante de l'ACP et \ndes surprises des OIS 1M, 1Y et 5Y")
```

```{r}
# Fonction de rotation des facteurs (on s'inspire du github de Martin Baumgaertner)

scale=apply(F[,2:3], 2, sd)
loading=loadings_matrix[,1:2]*scale
factors=as.matrix(sweep(F[,2:3],2, scale, "/"))

# Fonction des contraintes de la matrice de rotation 
con=function(x){
    f=NULL
    #orthogonal restrictions
    f=rbind(f,x[1]^2 + x[3]^2 - 1) 
    f=rbind(f,x[2]^2 + x[4]^2 - 1)
    f=rbind(f,x[1]*x[2] + x[3]*x[4] - 0)
    #second and third factors does not load on one month rate
    f=rbind(f,x[2]*loading[2,1] + x[4]*loading[2,2] -0) 
    # ici il met plutôt "rbind(f,x[3]*loading[1,1] + x[4]*loading[1,2] -0)", mais je crois qu'il se plante dans les indices de x ...
    return(list(ceq=f,c=NULL))
}

 obj<-function(x){
      U=matrix(c(x[1],x[2],x[3],x[4]),nrow=2)
      xx<-factors%*%U[,2]

      out<-0.5*t(xx)%*%xx/length(xx)
      as.numeric(out)
 }
 
sol<-solnl(c(diag(2)),objfun=obj,confun=con)
```

```{r}
# On finit la rotation en appliquant la matrice de rotation à F

rotate_factors<-factors%*%matrix(sol$par,nrow=2) %>%
    as_tibble(.,.name_repair = ~ vctrs::vec_as_names(..., repair = "unique", quiet = TRUE))

rotate_factors=rotate_factors%>%rename(F1=1, F2=2)%>% mutate(date=date) # à renommer proprement quand ce sera bien clair qui est qui (je crois que 2=Target, 1=FG)

full=merge(monetary_event_2012[1:15], rotate_factors, by="date")
```

```{r}
# Rescaling : à voir lequel à utiliser en fonction de qui est Target (je suppute que c'est F2)

scale_1=coef(lm(OIS_1M~F1, data = full))[2]
scale_2=coef(lm(OIS_1M~F2, data = full))[2]

rotate_factors=rotate_factors %>%mutate(F2 = F2*scale_2)
```

```{r}
# Evolution des rotate_factors
rotate_factors_2020=rotate_factors%>%mutate(year=year(rotate_factors$date), 
                  OIS_SW=monetary_event_2012$OIS_SW,
                  OIS_1M=monetary_event_2012$OIS_1M,
                  OIS_1Y=monetary_event_2012$OIS_1Y,
                  OIS_5Y=monetary_event_2012$OIS_5Y)%>%filter(year>=2020)

ggplot(rotate_factors_2020,aes(x=date))+
  geom_line(aes(y=F1, color="First_Dimension"))+
  geom_line(aes(y=F2, color="Second_Dimension"))+
  scale_color_manual(values=c(First_Dimension="cadetblue4", Second_Dimension="brown4"), labels=c("Dimension 1","Dimension 2"), name="Légende")+
  labs(x="Dates des annonces monétaires", y="Componsantes de l'annonce")+
  theme_bw()+
  ggtitle("Evolution temporelle des deux composantes de l'annonce \nmonétaire après rotation")
```



```{r}
# Tentative de rotation 2

# On veut récupérer le vecteur Z tel que Z=FU où U est la matrice de rotation adaptée.Pour construire U on se réfère à "The impact of ECB monetary policy decisions and communication on the yield curve"

gamma1=loadings_matrix[2,1] 
gamma2=loadings_matrix[2,2]
alpha1=gamma1/(gamma1+gamma2) 
alpha2=gamma2/(gamma1+gamma2)
beta1=-alpha2*var(F2)/(alpha1*var(F1)-alpha2*var(F2))
beta2=alpha1*var(F1)/(alpha1*var(F1)-alpha2*var(F2))

# ATTENTION : il faut avant standardiser les colonnes de U

U=cbind(c(alpha1,alpha2),c(beta1,beta2))

z1=alpha1*F1+alpha2*F2 
z2=beta1*F1+beta2*F2

Z=cbind(date,z1,z2)
```

```{r}
# Tentative de rotation 3

# Matrice de rotation d'après mes calculs à la main
gamma=sqrt(gamma1^2+gamma2^2) 
a=gamma1/gamma 
b=gamma2/gamma 
c=-b 
d=a
U_main=cbind(c(a,b),c(c,d)) 
z1_main=a*F1+b*F2 
z2_main=c*F1+d*F2
Z_main=cbind(date,z1_main,z2_main)

```

```{r}
# Les différentes bases de données possibles avec les facteurs trouvés
df_final_main=merge(monetary_event_2012, Z_main, by="date")
df_final=merge(monetary_event_2012, Z, by="date")

press_release_final=merge(press_release_2012, Z, by="date")
press_conference_final=merge(press_conference_2012, Z, by="date")

press_release_final_main=merge(press_release_2012, Z_main, by="date")
press_conference_final_main=merge(press_conference_2012, Z_main, by="date")

```

```{r}
# Pour arrêter de se prendre la tête avec 20 000 dataframes
PR=press_release_final%>%merge(Z_main, by="date")%>%merge(F, by="date")
MP=df_final%>%merge(Z_main, by="date")%>%merge(F, by="date")
PC=press_conference_final%>%merge(Z_main, by="date")%>%merge(F, by="date")

```

```{r}
# Vérification des corrélations entre la première dimension et chacune des deux fenêtres d'annonce

model_PR1=lm(as.formula(paste("z1 ~", paste(vars_PR, collapse = "+"))), data=press_release_final)
summary(model_PR1)

model_PR1_main=lm(as.formula(paste("z1_main ~", paste(vars_PR, collapse = "+"))), data=press_release_final_main)
summary(model_PR1_main)

```
La press-release explique plus (R² plus élevé égal à 0.4 contre 0.17) le deuxième facteur que le premier dans les deux cas. 

```{r}
model_PR2=lm(as.formula(paste("z2 ~", paste(vars_PR, collapse = "+"))), data=press_release_final)
summary(model_PR2)

model_PR2_main=lm(as.formula(paste("z2_main ~", paste(vars_PR, collapse = "+"))), data=press_release_final)
summary(model_PR2_main)
```

```{r}
model_PC1=lm(as.formula(paste("z1 ~", paste(vars_PC, collapse = "+"))), data=press_conference_final)
summary(model_PC1)

model_PC1_main=lm(as.formula(paste("z1_main ~", paste(vars_PC, collapse = "+"))), data=press_conference_final_main)
summary(model_PC1_main)
```

```{r}
model_PC2=lm(as.formula(paste("z2 ~", paste(vars_PC, collapse = "+"))), data=press_conference_final)
summary(model_PC2)

model_PC2_main=lm(as.formula(paste("z2_main ~", paste(vars_PC, collapse = "+"))), data=press_conference_final)
summary(model_PC2_main)
```
La press conference explique mieux ici le premier facteur que le deuxième (R² de 0.55 contre 0.39).


```{r}
PR$F1
```



```{r}
# Scaling
# Selon l'article "Measuring Euro Area Monetary Policy", on pondère les vecteurs trouvés, pour que une augmentation de un point de z1 soit associée à une augmentation de 1% du 1 month OIS  et qu'une augmentation de un point de z2 soit associée à une augmentation de 1% du 2 year OIS.

scaling_vector1=press_conference_2009$OIS_1M 
scaling_vector2=press_conference_2009$OIS_2Y

reg=lm(OIS_1M~z1_main, data=df_final)

summary(reg)
```

```{r}
plot1=ggplot(df_final, aes(x = z1_main, y = OIS_1M))+
  geom_point()

plot2=ggplot(df_final2, aes(x = z1, y = OIS_1M))+
  geom_point(color='blue')

```

